### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by ben-auo** [jacopodl/dstar#3]
```
[ 78%] Building CXX object CMakeFiles/dstar.dir/src/Core.cpp.o
/tmp/dstar/src/Core.cpp:20:10: fatal error: zconf.h: No such file or directory
   20 | #include <zconf.h>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dstar.dir/build.make:90: CMakeFiles/dstar.dir/src/Core.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:140: CMakeFiles/dstar.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by ben-auo** [comment]
P.S. to get the https://github.com/jacopodl/Spark/issues/1 fix you need to run `git submodule update --init --recursive --remote` instead of `git submodule init && git submodule update`

**Comment by jacopodl** [comment]
I've updated the project by removing the inclusion of zconf.h, as it doesn't appear to be used in the codebase, I've compiled the project without encountering any errors.

Can you check if the change fixed your problems? If you don't find any, I'll proceed to close the issue. Let me know!

**Comment by ben-auo** [comment]
That worked great, thanks!
